[package]
name = "chunked_transfer"
version = "0.3.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
repository = "https://github.com/frewsxcv/rust-chunked-transfer"
description = "Encoder and decoder for HTTP chunked transfer coding (RFC 7230 ยง 4.1)"
