language: rust

sudo: false

# run builds for all the trains (and more)
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failure:
    - rust: nightly

# load travis-cargo
before_script:
  - |
      export TRAVIS_CARGO_NIGHTLY_FEATURE="" &&
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only nightly test -- --features specialized &&
      travis-cargo bench

after_success:
  # measure code coverage and upload to coveralls.io
  - travis-cargo coveralls --no-sudo --verify

# necessary for pushing github docs
env:
  global:
  - secure: "sK8Vz18E5bqkpWc4yRRmZGWOf8Z5Lp8yKFEq8z9nXPY6XTCOmR5Pf2Zh82wFWwxBYILxfmoONaEDNWE0CHv0grbTX3Cv613wd9mgTi/MyV/O1wC2E52S8JE+JbiHcImqFjhr0ycafvLL+hSSY0/h8ZCkektzu/1Ut2ahPmT+KZI="

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls
