test = [{name = "tests", path = "tests.rs"}]

[package]
name = "ascii"
version = "0.7.1"
authors = ["Thomas Bahn <thomas@thomas-bahn.net>",
           "Torbjørn Birch Moltu <t.b.moltu@lyse.net>",
           "Simon Sapin <simon.sapin@exyr.org>"]

description = "ASCII-only equivalents to `char`, `str` and `String`."
documentation = "https://tomprogrammer.github.io/rust-ascii/ascii/index.html"
license = "Apache-2.0 / MIT"
repository = "https://github.com/tomprogrammer/rust-ascii"

[features]
no_std = []
